const express = require('express');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.post('/generate-blog', (req, res) => {
  const topic = req.body.topic;
  const blog = `Here's a blog post about ${topic} generated by AI.`;
  res.json({ blog });
});

app.get('/', (req, res) => {
  res.send('AI Creator Backend is live!');
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
