const express = require("express");
const app = express();
const port = process.env.PORT || 3000;

app.use(express.json());

app.get("/", (req, res) => {
  res.send("AI Assistant is online.");
});

app.post("/generate-blog", (req, res) => {
  const { topic } = req.body;
  const blog = `Here’s a blog post about ${topic} generated by AI.`;
  res.send(blog);
});

app.post("/push-to-github", (req, res) => {
  // Placeholder for GitHub API integration
  res.send("Pretend I just pushed your code to GitHub.");
});

app.listen(port, () => {
  console.log(`AI Assistant running on port ${port}`);
});
